# Generated by Django 5.2.3 on 2025-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('Call Drop', 'Call Drop'), ('Slow Internet', 'Slow Internet'), ('SMS Failure', 'SMS Failure'), ('No Network', 'No Network')], max_length=100)),
                ('description', models.TextField()),
                ('complaint', models.TextField(default='No complaint entered')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
