# Generated by Django 5.2.3 on 2025-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
