# Generated by Django 5.2.3 on 2025-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0002_alter_complaint_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
