# Generated by Django 5.2.3 on 2025-08-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0004_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
