# Generated by Django 5.2.3 on 2025-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0007_complaint_user_alter_complaint_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
