# Generated by Django 6.0.6 on 2026-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0008_complaint_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint',
        ),
    ]
