# Generated by Django 6.1 on 2026-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomcomplaints', '0010_emailverification_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='service_type',
            field=models.CharField(choices=[('Call Drop', 'Call Drop'), ('Slow Internet', 'Slow Internet'), ('SMS Failure', 'SMS Failure')], max_length=100),
        ),
    ]
